### ISSUE TITLE
ASP.NET Core SPA Angular 7 server side rendering SSR

### ISSUE THREAD

**Issue by ahamidou** [aspnet/AspNetCore.Docs#9398] opened 2018-11-02 02:21 UTC
I was able to successfully create an Angular 7 SPA rendering on the client side, There's no documentation however for how to render it on the server side.
The only documentation I found is kind of obsolete today because it's for older versions of Angular, 

Can we have the above content updated to reflect Angular 7 SSR?

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio#server-side-rendering)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment] 2018-11-02 11:39
Hello @ahamidou ... This looks to be a duplicate issue, and there might be existing duplicates.

* Document how to setup server side rendering with Angular Template #7971
* Add documentation for Server Side rendering from Angular templates #7310
* master issue:Update to angular 6 #8816 (request to skip 6 and go straight to 7)
* Update Angular SSR docs to match updated Angular 6 template #8139

**Comment by ahamidou** [comment] 2018-11-03 23:12
@guardrex I don't agree it's a duplicate 100%, this is about the latest version, Angular 7.
I even tried the above referenced issues, they were no help for me to get SSR to work by any means, so that's why I opened this issue.
On the other hand, let's agree that they're all duplicates... in which case how why don't we consolidate them and update the documentation once and for all?
Thank you!

**Comment by guardrex** [comment] 2018-11-03 23:17
One of the issues (#8816) is for 6 (6 was the latest at the time), and it has a post asking to just skip to 7. Others deal with SSR.

I agree that these might be consolidated in some way. @scottaddie will know the best way to handle these issues.

**Comment by BeejeeDS** [comment] 2018-11-04 16:35
I have been waiting for 3 months to finally see an updated version of the documentation. As of today we still have no clue how to make things work to successfully achieve SSR...

**Comment by Rick-Anderson** [comment] 2018-11-08 18:17
Closing duplicate

**Comment by blogcraft** [comment] 2019-01-03 04:18
I get this is closed, but which one has the solution? I cant get SSR on 2.2 and Ng 7, and the docs are still outdated.

**Comment by riaadh** [comment] 2019-01-21 15:06
please update the documentation this is is still not solved

**Comment by joshberry** [comment] 2019-01-23 23:35
I too was struggling to get SSR working with latest template. I ended up starting from scratch with asp.net core 2.2 and angular 7.2. It was surprisingly straightforward and I was even able to get SSR working on the server without the need to deploy node_modules. 

You can find the example here if you're interested: https://github.com/joshberry/dotnetcore-angular-ssr.

I'd be interested to know if you see any issues with or shortcomings of the setup.

**Comment by joshberry** [comment] 2019-01-25 14:51
@ahamidou I could take a look at updating the docs here, but it sounds like MS already has someone working on it. If they don't, I'd be happy to take a stab at it.

The project was basically put together by reading through the [Angular Universal](https://angular.io/guide/universal) and [JavaScriptServices](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-2.2) docs and browsing through dozens of github issue reports related to angular ssr on dotnet core, gleaning what I could from them. Obviously the current angular template was also a very helpful guide.

Hopefully the official template gets updated to the latest versions soon and they don't drop support for SSR (it appears some don't think it's important but for me it is critical). In the meantime, it's not too difficult to set it up on your own and it really helped me understand the moving parts much better.

**Comment by PieterjanDeClippel** [comment] 2019-07-16 21:26
I successfully wrote a reproducable article on Medium. Can you please append this content in the MS docs? It would probably help a lot of people...
Article: https://medium.com/@pieterjandeclippel/server-side-rendering-in-asp-net-core-angular-6df7adacbdaa
Final code with steps: https://github.com/PieterjanDeClippel/AspNetCoreSpaPrerendering

**Comment by Rick-Anderson** [comment] 2019-07-16 21:47
@scottaddie  should we check with the PU on getting : https://medium.com/@pieterjandeclippel/server-side-rendering-in-asp-net-core-angular-6df7adacbdaa migrated to the docs?

@PieterjanDeClippel  if they approve, we'd need you to make a PR of the content. You could copy/paste the HTML and we could do the MD conversion.

**Comment by SteveSandersonMS** [comment] 2019-07-17 09:46
@Rick-Anderson It would be reasonable to link to this, but I'd be cautious about actually copying the content into our docs. The issue is that this is a guide to using multiple third-party libraries together (`@nguniversal/express-engine` and Angular itself), which could have breaking changes at any moment. Who's responsible for keeping track of breaking changes and updating the content in the docs each time that happens?

**Comment by Rick-Anderson** [comment] 2019-09-23 21:35
Closing as we're on to 3.0 now
`Server-side rendering in ASP.NET Core Angular` is very discoverable

**Closed by Rick-Anderson** 2019-09-23 21:35 UTC
Labels: Source - Docs.ms

**Comment by dtabaka** [comment] 2019-09-27 11:56
Hi, I guess I'm still clear on the SSR with 3.0.   I ran the  package.json's  "build:ssr": "ng run AspNetCore3:server:dev" to generate main.js the ClientApp\dist-server.  (I'd like to know what the AspNetCore3:server:dev actually does)

I also set the <BuildServerSideRenderer>true</BuildServerSideRenderer> in my .csproj

What else do I have to do to get it run locally?
