### ISSUE TITLE
Page is clearly not updated for .NET Core 3.0 Endpoint Routing

### ISSUE THREAD

**Issue by jhudsoncedaron** [aspnet/AspNetCore.Docs#14893] opened 2019-10-07 18:39 UTC
Page is clearly not updated for .NET Core 3.0 Endpoint Routing: It's littered with UseMvc() everywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-10-07 18:57
Duplicate of https://github.com/aspnet/AspNetCore.Docs/issues/13871.

**Closed by guardrex** 2019-10-07 18:57 UTC
Labels: Source - Docs.ms
