### ISSUE TITLE
SSL Certificate Error when following guide

### ISSUE THREAD

**Issue by Faolan-dimplex** [aspnet/AspNetCore.Docs#13122] opened 2019-07-05 11:38 UTC
Followed the guide to the letter. After passing Step 8 was met with SSL errors, could not view the site:

    Chrome- "ERR_SSL_PROTOCOL_ERROR"
    IE11/Edge- "Can’t connect securely to this page" 
    Firefox- "SSL_ERROR_RX_RECORD_TOO_LONG"

Hopefully some silly configuration on my end, but I can't seem to find a solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-07-05 11:53
Hello @Faolan-dimplex ... What is the output of `dotnet --info`, and what browser versions are you using? Is your system date/time correct?

**Comment by Faolan-dimplex** [comment] 2019-07-05 11:59
C:\>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

Chrome: 75.0.3770.100
Microsoft Edge: 44.17763.1.0
IE: 11.504.17763.0
Firefox: 67.0.4

**Comment by guardrex** [comment] 2019-07-05 12:00
... and the system date/time is correct, right?

**Comment by Faolan-dimplex** [comment] 2019-07-05 12:00
Yes, sorry, forgot to add that, System Date/Time is correct

**Comment by guardrex** [comment] 2019-07-05 12:12
Sounds like the development cert has some sort of problem ... corrupt or missing.

1. In the Windows Search box, type "cert" and select **Manage computer certificates**.
1. In the **Personal** cert store, do you see one with a friendly name of "ASP.NET Core HTTPS development certificate"?

**Comment by Faolan-dimplex** [comment] 2019-07-05 12:19
No, I have one listed as "IIS Express Development Certificate" which is valid

**Comment by guardrex** [comment] 2019-07-05 12:20
Missing then.

Try re-installing the 3.0 Preview 6 SDK (64-bit). Make sure you're using an admin system account when you run the installer.

https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by guardrex** [comment] 2019-07-05 12:24
If it's a corporate machine and you can't be an admin for the install, you'll probably need your IT cats to come in and run the installer using one of their accounts.

**Comment by Faolan-dimplex** [comment] 2019-07-05 12:26
Uninstalled/Reinstalled, making sure to run as administrator, Still don't seem to have the cert

**Comment by guardrex** [comment] 2019-07-05 12:35
Ok ... let's get you over to the engineers for more investigation and assistance.

Open an issue on the engineering repo for the engineers to take a look at:

* Paste in your opening comment here with the browser errors.
* Paste that `dotnet --info` into the issue.
* Tell them that the system date/time is correct.
* Mention that you tried a Preview 6 re-install.
* Mention that you don't see the "ASP.NET Core HTTPS development certificate" cert listed in the Personal store.

https://github.com/aspnet/AspNetCore/issues

I suspect that they'll work with you to research in the logs what's going on with the cert install.

Add "cc: @guardrex" at the bottom so that I get pinged and can follow along.

I'll close this since it seems like it won't be a doc issue, but we can re-open later if we find out something that we do need to document.

**Closed by guardrex** 2019-07-05 12:35 UTC
Labels: Blazor, P4, Source - Docs.ms

**Comment by guardrex** [comment] 2019-07-05 12:48
@Faolan-dimplex Note one more thing. They may have **used to** place the cert in the machine's store. I just checked my **Current User** store and found a more recent dev certs in there ...

<img width="657" alt="Capture" src="https://user-images.githubusercontent.com/1622880/60723409-27020580-9ef9-11e9-933c-87e13dca6bca.PNG">

The one I have in the machine store might be from an old ANCM hosting bundle installer run.

Anywho ... they'll help figure out what the problem is.
