### ISSUE TITLE
Please add this example for parent-child with complex object two-way binding

### ISSUE THREAD

**Issue by VR-Architect** [aspnet/AspNetCore.Docs#13651] opened 2019-08-04 17:11 UTC
Here is some sample code I wrote to use a complex object with two-way binding from parent-child. It also shows TypeConverting for the custom class for passing in the bind.

```
    using System.ComponentModel;
    [TypeConverter(typeof(MyClassConverter))]
    public class MyClass
    {
        public string Property1 { get; set; }
        public int Property2 { get; set; }
        public MyClass(string p1, int p2)
        {
            Property1 = p1;
            Property2 = p2;
        }
    }
```

```
   using System;
   using System.ComponentModel;
   using System.Globalization;

    [TypeConverter(typeof(MyClassConverter))]
    public class MyClassConverter : TypeConverter
    {
        public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
        {
            if (sourceType == typeof(string))
            {
                return true;
            }
            return base.CanConvertFrom(context, sourceType);
        }
        public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
        {
            if (value is string)
            {
                return new MyClass("", Int32.Parse(value.ToString()));
            }
            return base.ConvertFrom(context, culture, value);
        }
        public override object ConvertTo(ITypeDescriptorContext context, CultureInfo culture, object value, Type destinationType)
        {
            if (destinationType == typeof(string)) { return "___"; }
            return base.ConvertTo(context, culture, value, destinationType);
        }
    }
```

```
@page "/"

<div style="border: double; padding: 5px;">
    <h1>Parent Component</h1>
    <p>Parent Property1: @ParentMyClass.Property1</p>
    <p>Parent Property2: @ParentMyClass.Property2</p>
    <button class="btn btn-primary" @onclick="ChangeTheData">
        Change the data from Parent
    </button>
</div>
<br />
<div style="border: double; padding: 5px;">
    <Child @bind-myClass="ParentMyClass" @onchange="RefreshParent" />
</div>

@code{
    private MyClass ParentMyClass { get; set; } = new MyClass("Initial data before changed", 2000);
    private void RefreshParent(UIChangeEventArgs args)
    {
        StateHasChanged();

        // If you need access to which property changed in the child and its value
        string changedProperty = args.Type;
        var changedValue = args.Value;
         
    }
    private void ChangeTheData()
    {
        ParentMyClass.Property1 = "I got changed by the parent";
        ParentMyClass.Property2 = 1776;
    }
}
```

```
<h2>Child Component</h2>
<p>Child Property1: @myClass.Property1</p>
<input type="text" @onchange="Property1Changed" value="@myClass.Property1" />
<p>Child Property2: @myClass.Property2</p>
<input type="number" @onchange="Property2Changed" value="@myClass.Property2" />

@code {
    [Parameter] private MyClass myClass { get; set; }
    [Parameter] public EventCallback<UIChangeEventArgs> MyClassChanged { get; set; }
    [Parameter] public EventCallback<UIChangeEventArgs> OnChange { get; set; }

    private async Task Property1Changed(UIChangeEventArgs args)
    {
        myClass.Property1 = args.Value.ToString();
        args.Type = "Property1";
        await OnChange.InvokeAsync(args);
    }
    private async Task Property2Changed(UIChangeEventArgs args)
    {
        if (int.TryParse(args.Value.ToString(), out int iValue))
        {
            myClass.Property2 = iValue;
            args.Type = "Property2";
            await OnChange.InvokeAsync(args);
        }
    }
}
```

**Comment by VR-Architect** [comment] 2019-08-04 17:14
Note the above example is missing one concept. If the value entered by the user is invalid, how to reset the child input to the value in the class. I was able to figure that out. To try that, just change Property2 to a input type text then enter a non-integer value.

**Comment by guardrex** [comment] 2019-08-04 17:18
Thanks @VR-Architect ... This seems like a duplicate of https://github.com/aspnet/AspNetCore.Docs/issues/13539. Why didn't you add this to that issue?

**Comment by VR-Architect** [comment] 2019-08-04 17:21
@guardrex Sorry, I didn't know about that one. Please feel free to close this if needed.

**Comment by guardrex** [comment] 2019-08-04 17:21
Do you plan to move this to a comment over there, or would you like me to move it?

**Comment by guardrex** [comment] 2019-08-04 17:23
I suppose a cross-link to this is ok. It would have been a bit more visible to just paste it all into a new comment over there.

**Comment by VR-Architect** [comment] 2019-08-04 17:23
I moved it. thanks again

**Closed by guardrex** 2019-08-04 17:23 UTC
Labels: Blazor, Source - Docs.ms
