### ISSUE TITLE
Capitalization error/Mismatch 

### ISSUE THREAD

**Issue by LouisT123** [aspnet/AspNetCore.Docs#13562] opened 2019-07-30 23:18 UTC
Capitalization error in the code that is supposed to be copied. Should be "ID" not "Id" for this section: [Add validation rules to the movie model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.2&tabs=visual-studio#add-validation-rules-to-the-movie-model)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by LouisT123** [comment] 2019-07-30 23:28
@Rick-Anderson Can you review the PR and merge it?
/cc: @anangaur

**Comment by Rick-Anderson** [comment] 2019-07-30 23:33
What PR?

We've decide to not change `ID` to `Id`, although `Id` is preferable.

**Comment by anangaur** [comment] 2019-07-31 00:06
The issue is that rest of the code examples use “ID” while this one uses “Id” and this seems to break the build if one follows the doc and copies the code as is. The change was to change this too to “ID”.

**Comment by Rick-Anderson** [comment] 2019-07-31 00:29
Thanks @anangaur  - I read that too quickly.

**Comment by Rick-Anderson** [comment] 2019-07-31 15:16
Fixed in #13563

**Closed by Rick-Anderson** 2019-07-31 15:16 UTC
Labels: Source - Docs.ms
