### ISSUE TITLE
How to use resources in seperate project?

### ISSUE THREAD

**Issue by stg609** [aspnet/AspNetCore.Docs#12492] opened 2019-05-22 01:56 UTC
Tried different ways, but no luck. Hope there's a sample solution tell us how to make it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#additional-resources)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2019-05-22 03:52
@stg609  tried what? What didn't work? What did you expect?

**Comment by stg609** [comment] 2019-05-22 04:26
What did I expected?We created a common project to hold all the resources.

**Comment by stg609** [comment] 2019-05-22 04:38
**What did I expected?**
We expect there's an official guideline to show us how to make use of the localized resource in a seperate project. Because we can't get it to work after google a lot.

**What did work?**
Following the [doc](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2), we can get the localized string as expected. But after we moved the whole resources folder to another project, than we can't get the localized string anymore.

**What did we tried?**
1、Ensure the project name is the same as the default assembly name
2、Create a AssemblyInfo.cs, and add `[assembly: ResourceLocation("Resources")]`
3、Remove the ResourcePath when calling services.AddLocalization

None of them works.

**Comment by hishamco** [comment] 2019-06-05 05:12
@stg609 did you check the [troublshooting](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/troubleshoot-aspnet-core-localization?view=aspnetcore-2.2) section before I dig into your code?

**Comment by Rick-Anderson** [comment] 2019-06-05 18:58
This is not a localization issue. It's a getting resources from another project issue that should probably be opened with Visual Studio feedback.

**Comment by hishamco** [comment] 2019-06-05 19:09
This may caused by `ResourceLocation`, `RootNamespace` or miss localization configuration

**Comment by LazZiya** [comment] 2019-07-08 07:09
> Tried different ways, but no luck. Hope there's a sample solution tell us how to make it.

I've created a sample repo with resources in external project, you may see it [here](https://github.com/LazZiya/ExpressLocalizationSample/tree/v0.0.3). 

It shows localization for views, DataAnnotations, IdentityErrors and ModelBinding error messages all using shared resources from external project. 

_Notice: In the [releases](https://github.com/LazZiya/ExpressLocalizationSample) after [v0.0.3](https://github.com/LazZiya/ExpressLocalizationSample/tree/v0.0.3) I moved the resources to the main project folder just to simplify the sample for beginners._

**Comment by hishamco** [comment] 2019-08-02 02:52
@Rick-Anderson can we closed this while the issues has been answered and there's no respond from the author

**Closed** 2019-08-02 19:35 UTC
Labels: P2, PU, Source - Docs.ms

**Comment by okofahi** [comment] 2019-12-20 16:31
i still cannot resolve this issue.
The main project cannot display the localized strings from the Models class library.

**Comment by hishamco** [comment] 2019-12-20 16:38
@okofahi do you a repo that reproduce the bug, but before that please check the troubleshooting  guidance
