### ISSUE TITLE
Nginx Ingress to Kubernetes

### ISSUE THREAD

**Issue by CeciAc** [aspnet/AspNetCore.Docs#12356] opened 2019-05-09 18:33 UTC
@alexsandro-xpt commented on [Thu May 09 2019](https://github.com/aspnet/AspNetCore.Docs.pt-br/issues/111)

Seria muito válido enfatizar neste documento se sim ou não se o Nginx Ingress do Kubernentes envia por padrão os cabelhaços X-Forwarded-For,  X-Forwarded-Proto e X-Forwarded-Host mesmo dizendo acima que: Por convenção, os proxies encaminham informações em cabeçalhos HTTP.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure o ASP.NET Core para trabalhar com servidores proxy e balanceadores de carga](https://docs.microsoft.com/pt-br/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/aspnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

---

@guardrex commented on [Thu May 09 2019](https://github.com/aspnet/AspNetCore.Docs.pt-br/issues/111#issuecomment-490863714)

Thanks @alexsandro-xpt ... Mudei isso para o nosso repositório. https://github.com/aspnet/AspNetCore.Docs/issues/12349

**Comment by CeciAc** [comment] 2019-05-09 18:36
Hi team, 
I'm moving this here since the user is making a suggestion on the original documentation
Translation:

> It would be very valid to emphasize in this document whether or not the Nginx Ingress of Kubernentes sends by default the X-Forwarded-For, X-Forwarded-Proto, and X-Forwarded-Host even saying above: By convention, proxies forward information in HTTP headers.

**Comment by guardrex** [comment] 2019-05-09 21:34
Duplicate of #12349

**Closed by guardrex** 2019-05-09 21:34 UTC
Labels: PU, Source - Docs.ms
