### ISSUE TITLE
Problem with breakpoints

### ISSUE THREAD

**Issue by VILcryo** [aspnet/AspNetCore.Docs#16112] opened 2019-12-10 11:26 UTC
I did everything as was written in this article, but could not set breakpoints  for the code lines  in razor files on the source tab. I tried a right click on the lines, saw the Breakpoint word in pop-up menu, but it was inactive. What's wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-12-10 13:45
I was just working with this yesterday morning, and I think I'm close to working it out based on the blog post instructions. I placed my current approach on the issue.

Let's close this as a duplicate of that issue. I'm planning on working on it more today. If I can't get it running, we'll get input from engineering on that issue.

https://github.com/aspnet/AspNetCore.Docs/issues/15983

**Closed by guardrex** 2019-12-10 13:45 UTC
Labels: :watch: Not Triaged, Blazor, Source - Docs.ms
