### ISSUE TITLE
HTTP/2 is not disabled by default in Kestrel 3.0

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore.Docs#14018] opened 2019-08-26 09:14 UTC
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.0#http2-support

> HTTP/2 is disabled by default.

In 3.0 endpoints are HTTP/1.1 or HTTP/2 by default.

@Tratcher

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.0&branch=pr-en-us-14015#http2-support)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-08-26 11:18
Duplicate of https://github.com/aspnet/AspNetCore.Docs/issues/10141.

**Closed by guardrex** 2019-08-26 11:18 UTC
Labels: Source - Docs.ms

**Comment by imba-tjd** [comment] 2019-11-04 12:17
This issue still exists?
