### ISSUE TITLE
How To "Download or view the completed application."

### ISSUE THREAD

**Issue by edikaufmann** [aspnet/AspNetCore.Docs#13404] opened 2019-07-19 13:02 UTC
thanks for taking the time …
each chapter has a 'link' saying:
"Download or view the completed application."
when clicking I get to github. Yes I see the github files BUT I can't 'download' (NO 'clone and Download' button).
VIEW: does this just mean to view the github files!?
HOW do I view the App !?
Is it possible to download the finished app!?
What I'm doing wrong NOT to see the 'Clone or Download' button ?
thanks ek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [Tutorial: Implement inheritance - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment] 2019-07-19 15:16
Duplicate of https://github.com/aspnet/AspNetCore.Docs/issues/13403

**Closed by guardrex** 2019-07-19 15:16 UTC
Labels: Source - Docs.ms
