### ISSUE TITLE
Highlighted bits are masking out the code in examples

### ISSUE THREAD

**Issue by WhitWaldo** [aspnet/AspNetCore.Docs#13197] opened 2019-07-08 20:43 UTC
Within many of the code examples on this page, only bits and pieces of the code is actually visible on the page within any of the bright yellow highlight boxes. It's there when looking at the page source, but the CSS appears to be hiding it (for the most part).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cce372-24e2-3489-cb19-c85d934e5d3b
* Version Independent ID: 9d12b19f-a94e-4df4-357b-3f3b93696eb6
* Content: [Test controller logic in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/controllers/testing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/testing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment] 2019-07-08 21:05
Closing as a duplicate of https://github.com/aspnet/AspNetCore.Docs/issues/13143. Engineering is testing a fix and hopes to deploy it soon.

**Closed by scottaddie** 2019-07-08 21:05 UTC
Labels: Source - Docs.ms
