### ISSUE TITLE
AddAzureWebAppDiagnostics Logging Provider not honoring filters

### ISSUE THREAD

**Issue by fvilches17** [aspnet/AspNetCore.Docs#15212] opened 2019-10-19 14:03 UTC
E.g. 

1. Set appsettings.json like so:
"Logging": {
    "LogLevel": {
      "MyNamespace.*": "Debug",
      "Default": "Error"
    }
  }

2. Run web app locally and see only you own logs printed to the console.

3. Add AddAzureWebAppDiagnostics to logging in program.cs

4. Deploy your asp.net core app (in my case I tried 2.2 and 3.0)

5. Enable logs in AppService logs for your web app in azure portal. Log level = Information

6. Watch logs come in. You notice ALL logs (e.g. Microsoft.*) come in.

You can also refer here
https://stackoverflow.com/questions/42789154/filtering-logs-in-azure-web-app-diagnostics-logs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by buttons019** [comment] 2019-11-19 19:47
Hi, I found the same issue.
I'd like to know (sorry for my lack of experience) whether this is being treated as a bug or differently and when a solution is planned to be available. I had to suspend logging on an almost live app and need to reestablish it. Thanks,

**Comment by Rick-Anderson** [comment] 2019-11-19 20:34
@Tratcher  should you transfer this to https://github.com/aspnet/AspNetCore/issues ?
I'd do it but I don't have write permission to your repo.

**Comment by Rick-Anderson** [comment] 2019-11-19 20:50
@fvilches17 @buttons019  see #14924

**Comment by Tratcher** [comment] 2019-11-19 21:00
Looks like a duplicate of https://github.com/aspnet/AspNetCore/issues/3279

**Comment by Rick-Anderson** [comment] 2019-11-19 21:34
@guardrex  see `@pakrym` answer

Diagnostic Logs Level is only used for Log streaming output. It doesn't apply to any other logging providers.

Can you add that to this doc?

**Comment by guardrex** [comment] 2019-11-19 21:38
Sure thing.

**Comment by buttons019** [comment] 2019-11-20 18:38
> @fvilches17 @buttons019  see #14924

@Rick-Anderson thanks for the reply and the link. Unfortunately it solves the problem for whoever cannot get the app to log, but not for me (and I think @fvilches17) cause we need to filter what's being already logged. Any hint on how to achieve that? Thanks again,

**Comment by guardrex** [comment] 2019-11-20 22:42
Fixed by https://github.com/aspnet/AspNetCore.Docs/pull/15772.

**Closed by guardrex** 2019-11-20 22:42 UTC
Labels: P1, Source - Docs.ms, doc-bug
