### ISSUE TITLE
Can we change the login page to Razor components instead of ASP.NET Core MVC area

### ISSUE THREAD

**Issue by sarathlalsaseendran** [aspnet/AspNetCore.Docs#15878] opened 2019-11-26 19:15 UTC
While creating a Blazor project with individual user account authentication, it is noticed that login page is still created as ASP.NET Core MVC area instead of Blazor component. Can we expect razor component template in coming days?. I feel that would be great. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-11-26 19:27
Hello @sarathlalsaseendran ... This is a duplicate of https://github.com/aspnet/AspNetCore.Docs/issues/13062, and we'll be taking a look at that soon. I don't have any info at the moment on their design plans in this area, but you could search the engineering repo to see what's there. Here's the direct link to Blazor issues ...

https://github.com/aspnet/AspNetCore/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-blazor

Right now, I don't have a recommended approach. There's a post on that issue from a reader who might have a good approach, so check that out.

**Closed by guardrex** 2019-11-26 19:27 UTC
Labels: :watch: Not Triaged, Source - Docs.ms

**Comment by guardrex** [comment] 2019-11-26 19:29
Here's an example ... this pertains to that subject:

https://github.com/aspnet/AspNetCore/issues/10883

**Comment by guardrex** [comment] 2019-11-26 19:31
More related info here :point_right: https://github.com/aspnet/AspNetCore/issues/5474
