### ISSUE TITLE
Make discussion and commentation easier 

### ISSUE THREAD

**Issue by eTaoss** [aspnet/AspNetCore.Docs#13675] opened 2019-08-01 16:00 UTC
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

Currently the discussions push away users, since they are runned as github issues. This forces many users to stop using the website instead getting helped with their issues by the rest of the community, or the guys which already finished the tutorials. In current way you need to go to the github, do some more reading, then you realize you would be pushing an issue, so you do not place a comment and rather go angrily away, since the issue is on readers side, but it feels wrong to create an issue because of that (and response time is also longer and not always at place since ammount of work on the team.)
This can lead to overwhelming the team taking care of the tutorials. 

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

Best solution for the readers would be placing option to leave a comment right on the tutorials page, no redirecting to the github issues. And there could be a dedicated button to reporting issues which would actually redirect to the github issues.

### Additional context
Solution of this could lead to happier community, with much easier learning, since many people have similar issues and easier and less stressing the commenting, easier and better solving :)

**Comment by danroth27** [comment] 2019-08-05 21:03
@Rick-Anderson @mairaw

**Comment by mairaw** [comment] 2019-08-05 21:09
It seems like it's about the feedback mechanism indeed. But folks don't need to come to GitHub to see the thread. They can just expand the comments right on the page.
For example:
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#feedback

![image](https://user-images.githubusercontent.com/12971179/62495333-6c308600-b78a-11e9-8601-77968e152ed6.png)

And you can also enter the comments right on the docs page too:
![image](https://user-images.githubusercontent.com/12971179/62495418-a8fc7d00-b78a-11e9-904d-2355dd60b33e.png)

I'd close this as by design if I'm understanding the issue correctly.

**Comment by Rick-Anderson** [comment] 2019-08-05 21:37
>  instead getting helped with their issues by the rest of the community,

Issues are not designed to solicit community help. When the issue is resolved and has helpful information that doesn't meet the bar of adding it to the article, it's still discoverable in the closed issues.

Note the preceding assume we are locking closed issues that are not helpful. We do that in the ASP.NET.docs repo. Only the 10 most current issues are displayed.

We're closing this by design.

**Closed by Rick-Anderson** 2019-08-05 21:37 UTC
