### ISSUE TITLE
Add more details in the middleware section for Map**

### ISSUE THREAD

**Issue by Nothing-Works** [aspnet/AspNetCore.Docs#15662] opened 2019-11-11 21:24 UTC
# Issue description

I think we should add more details for `MapWhen` in the middleware section. As it stops executing the rest of the pipeline when the delegate returns `true`. I do not think this is in the [docs](https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.0) and this can be confusing for new people.

Whereas `UseWhen` will not stop the execution and I can not find in the [docs](https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.0) either.  

Can I submit PR?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.0#use-run-and-map)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-11-11 21:45
Possibly a duplicate of (or an add on to) https://github.com/aspnet/AspNetCore.Docs/issues/15497.

**Comment by Rick-Anderson** [comment] 2019-11-11 22:25
Next time Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

@Nothing-Works  yes, please provide a PR that address this and `#4` on #15497

cc @serpent5

**Comment by djpandab** [comment] 2020-01-21 18:53
The title of this thread should read 
Add more details in the middleware section for Map** #15662
instead of
Add more deatils in the middleware section for Map** #15662

**Comment by serpent5** [comment] 2020-01-21 19:19
I think this can be closed. It was covered in #15497.

**Closed** 2020-01-21 19:19 UTC
Labels: doc-enhancement
