### ISSUE TITLE
Scaffolding Identity fails with _WriteAttribute does not exist in the current context 

### ISSUE THREAD

**Issue by khutch66** [aspnet/AspNetCore.Docs#12517] opened 2019-05-23 19:27 UTC
# Issue description

After generating a the default template for React + ASP.NET Core 3.0 MVC with authentication, I would like to scaffold out the identity items so that I can customize the login UI. Scaffolding identity results in the error Template Processing Failed (95,13) error CS0103: The name 'BeginWriteAttribute' does not exist in the current context
(96,13) The name 'EndWriteAttribute' does not exist in the current context

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [ X] .NET Core 3.00, ASP.NET Core React template with authentication. Attempting to scaffold Account\Login, Account\Logout, and/or Account\Register with the default ApplicationDbContext

**Comment by wickedlizerd** [comment] 2019-05-27 01:20
Same issue here.

**Comment by scottaddie** [comment] 2019-05-29 21:17
I'm able to reproduce the error too:

![image](https://user-images.githubusercontent.com/10702007/58591882-e7c30380-822c-11e9-8751-9932873bdbf5.png)

Closing as a duplicate of https://github.com/aspnet/Scaffolding/issues/997. Please track progress on the issue over there.

**Closed by scottaddie** 2019-05-29 21:17 UTC
Labels: P2
