### ISSUE TITLE
IHostingEnvironment is deprecated in favor of IWebHostEnvironment 

### ISSUE THREAD

**Issue by caihongxu** [aspnet/AspNetCore.Docs#15334] opened 2019-10-27 07:14 UTC
Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-10-27 09:15
Duplicate of https://github.com/aspnet/AspNetCore.Docs/issues/13331.

**Closed by guardrex** 2019-10-27 09:15 UTC
Labels: :watch: Not Triaged, Source - Docs.ms
