### ISSUE TITLE
Need information focused on the production of errors (especially accumulation of message

### ISSUE THREAD

**Issue by Paul-Dempsey** [aspnet/AspNetCore.Docs#15333] opened 2019-10-27 04:49 UTC
I want to make sure that my APIs generate rich error responses that contain good information about what they're done wrong. These docs are very lean on examples and instructions on the _generation_/_creation_ of errors. I'm particularly interested in accumulating multiple message during the processing of a response. Information on accomplishing this scenario is would be very helpful. Logging is related and helpful for the api provider, but error responses are for the api clients, and important to be high quality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.0)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by guardrex** [comment] 2019-10-27 09:01
Did you see this topic? https://docs.microsoft.com/aspnet/core/web-api/handle-errors

**Comment by Paul-Dempsey** [comment] 2019-10-27 14:48
Thanks Luke - Yes I did -- that is the page I opened the feedback on. Doesn’t a reference to the page automatically get included with the feedback? If not, that’s pretty broken.

It has info about about handling errors, and nothing on producing them. Sure you can raise an exception, but an exception is a one-off (not an accumulation)), and not clear how you set a particular htttp response code for a given error.

:- Paul

**Comment by guardrex** [comment] 2019-10-27 15:01
No, it does ... I missed it. We sometimes get requests for API error handling coverage from *the other page*. When I saw your post, I mistakenly asked about 'seeing the other topic,' realized my error, and deleted my remark.

Stand-by ... Rick will take a look and comment.

**Comment by mattiasw2** [comment] 2019-12-05 12:43
- Using aspnet core 3.0. I looked at aspnetcore/web-api/handle-errors.md and I cannot see any example of how to create an ProblemDetailsFactory. What am I missing?

- I would like to understand why "return BadRequest("missing id");" is not converted into a ProblemDetails json. Is this by design? Do I have to rewrite all BadRequest and NotFound and similar to Problem() like this:

`
      return NotFound($"ins id \'{id}\' does not exist");`

to

     return Problem(detail: "Instance doesn't exist", instance: id, 404, "Not found", type: Request.Path);

**Comment by mattiasw2** [comment] 2019-12-06 11:51
The "The status code above is 404, but I see 200 in my browser" has been fixed in 3.1

**Comment by Rick-Anderson** [comment] 2020-01-03 03:33
Moved to #16385

**Closed by Rick-Anderson** 2020-01-03 03:33 UTC
Labels: PU, Source - Docs.ms, doc-enhancement
