### ISSUE TITLE
Add must trust cert

### ISSUE THREAD

**Issue by Dave-Lowndes** [aspnet/AspNetCore.Docs#13552] opened 2019-07-30 13:09 UTC
When the client tries to communicate to the service, the service reports:

fail: Microsoft.AspNetCore.Server.Kestrel[0]
      HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.

Presumably the client code needs some subtle change to ensure it uses HTTP/2 ?
And the client crashes:

Unhandled exception. System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---&gt; System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the softwar
e in your host machine..
 ---&gt; System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.&lt;FillBufferAsync&gt;g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 t
ask, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolea
n doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken can
cellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts,
 Boolean disposeCts)
   at Grpc.Net.Client.Internal.GrpcCall`2.SendAsync(HttpClient client, HttpRequestMessage message)
   at Grpc.Net.Client.Internal.GrpcCall`2.GetResponseAsync()
   at GrpcGreeterClient.Program.Main(String[] args) in C:\Users\DLowndes\Source\Repos\GrpcGreeterClient\GrpcGreeterClient\Program.cs
:line 17
   at GrpcGreeterClient.Program.&lt;Main&gt;(String[] args)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by clarkezone** [comment] 2019-07-30 17:32
+1 this sample doesn't work

**Comment by Rick-Anderson** [comment] 2019-07-30 17:53
what version of .NET Core? 
`dotnet --version`

**Comment by Dave-Lowndes** [comment] 2019-07-30 19:32
3.0.100-preview7-012821

**Comment by Rick-Anderson** [comment] 2019-07-30 20:05
@Dave-Lowndes is this a dup of  #13120

**Comment by tehstun** [comment] 2019-07-30 20:55
@Rick-Anderson the duplicate work around does not make sense, could you provide more context?

**Comment by JamesNK** [comment] 2019-07-30 21:48
When you run the server sample, what is the console output. For example, this is what I see:

```
C:\Development\Source\AspNetCore.Docs\aspnetcore\tutorials\grpc\grpc-start\sample\GrpcGreeter [master ≡]> dotnet run
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Development\Source\AspNetCore.Docs\aspnetcore\tutorials\grpc\grpc-start\sample\GrpcGreeter
```

I want to verify that you have an HTTPS endpoint.

**Comment by Dave-Lowndes** [comment] 2019-07-30 22:37
@JamesNK I get precisely what's shown on the tutorial page - not what you showed there, specifically the "Now listening on http://localhost:5000" you have is not present for me.

**Comment by Rick-Anderson** [comment] 2019-07-30 22:40
@Dave-Lowndes see #13560

**Comment by Dave-Lowndes** [comment] 2019-07-30 22:44
@Rick-Anderson I have looked at that, but you're going to have to spell it out for me. I'm new to all this. What specifically needs to be done to make things work?

**Comment by JamesNK** [comment] 2019-07-30 22:50
> @JamesNK I get precisely what's shown on the tutorial page - not what you showed there, specifically the "Now listening on http://localhost:5000" you have is not present for me.

That's fine.

See my comment here - https://github.com/aspnet/AspNetCore.Docs/issues/13120#issuecomment-516598055

It looks like your server is using HTTPS so you should use this code to call the gRPC server:

```cs
    var httpClient = new HttpClient();
    // The port number(5001) must match the port of the gRPC server.
    httpClient.BaseAddress = new Uri("https://localhost:5001");
    var client = GrpcClient.Create<Greeter.GreeterClient>(httpClient);
```

**Comment by Dave-Lowndes** [comment] 2019-07-31 08:28
@JamesNK That code is precisely what the tutorial says to use for the client - and is what I have. It doesn't currently work for me.

**Comment by JamesNK** [comment] 2019-07-31 08:37
Sorry, I don't know what the problem is then. Perhaps a local firewall or some other networking software policy is preventing the connection. That's my only guess from your error message:

> An established connection was aborted by the software in your host machine.

**Comment by Dave-Lowndes** [comment] 2019-07-31 09:09
@JamesNK I'm seeing different behaviour on different machine's OS's - though neither I've tried work as the tutorial says it should.

On a current Windows 10 B18945 machine, when I run the server, it outputs:

info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\gRPCTest\Server

On a Windows 2008 R2 machine, it currently outputs:
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\DLowndes\Desktop\gRPCTest\Server

When the client tries to connect on the same Win 10 machine, there's nothing output by the server, and the client crashes with:

Unhandled exception. System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.

On the Windows 2008 R2 machine, when the client tries to connect, the server outputs:
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.

and the client crashes with:

C:\Users\DLowndes\Desktop\gRPCTest\Client>GrpcGreeterClient.exe
Unhandled exception. System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..

I'm using the same copied client/server builds on both machines.

**Comment by Dave-Lowndes** [comment] 2019-08-02 16:15
I've set up a clean Windows 10 1903 July VM, and have repeated this example on that and have finally got it to work.
Observations:
1. Until I've run the server component up in VS via F5, and have got the prompt to "Trust ASP.NET Core SSL Certificate", pressed Yes, and then installed the certificate, it doesn't work. Aspects around getting the certificate installed should probably be documented in this example?
2. On Windows 2008 R2, I still can't get it to work. I notice that platform isn't listed as supported (https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md), though Windows 7 SP1 is. Is there a good reason it's not supported other than it's just not been tested?

**Comment by JamesNK** [comment] 2019-08-02 22:19
1. Sure. We can improve docs in this area.
2. HTTP2 requires Win8.1+ for ALPN, and Win10 in most scenarios for ciphers. Win2008 R2 is missing required crypto support for HTTPS with HTTP2.

**Comment by Dave-Lowndes** [comment] 2019-08-02 23:27
@JamesNK 
1. Great.
2. So, presumably Windows 7 won't work either? I've not tried it.

**Comment by JamesNK** [comment] 2019-08-02 23:40
Win 7 won't work.

**Comment by tehstun** [comment] 2019-08-03 15:19
Just to add to the discussion about the docs being updated, there does not seem to be anything related to properly disposing of a client connection that uses the new methods of the light client base. 

```csharp
var client = GrpcClient.Create<client>(httpclient);
```

Its not clear if we just dispose of the httpclient or there are more steps to stop the server throwing a "System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host." error.

**Comment by AndreMantas** [comment] 2019-08-21 17:44
I'm having a similar problem. Here's the output from the server:

```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\andre.mantas\source\grpc-tests\GrpcGreeter
```

As on the example, its running on https and port 5001

But when I run the client:

```
Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)   
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, 
CancellationTokenSource cts, Boolean disposeCts)
   at Grpc.Net.Client.Internal.GrpcCall`2.SendAsync(HttpClient client, HttpRequestMessage request)      
   at Grpc.Net.Client.Internal.GrpcCall`2.GetResponseHeadersAsync()
   at GrpcGreeterClient.Program.Main(String[] args) in C:\Users\andre.mantas\source\grpc-tests\GrpcGreeterClient\Program.cs:line 17
   at GrpcGreeterClient.Program.<Main>(String[] args)
```

Currently using dotnet version:
`3.0.100-preview8-013656`

**Comment by Rick-Anderson** [comment] 2019-08-23 18:12
The sample is working now with `3.0.100-preview8-013656`

**Comment by JamesNK** [comment] 2019-08-23 21:21
> Found the problem: I was using vs code and running the server via terminal and it didn't ask me to install/trust the localhost certificate. Running on VisualStudio asked me to trust the certificate and now the client works as expected. Might add a note for readers using only vscode

@Rick-Anderson This looks like it is the underlying problem. Should the gRPC tutorial and troubleshooting page be updated to include a note that the ASP.NET Core HTTPS dev certificate needs to be trusted? Instructions here: https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos

**Comment by Rick-Anderson** [comment] 2019-09-23 21:30
@wadepickett  ping

**Comment by wadepickett** [comment] 2019-09-26 23:01
Sorry I missed this Rick! Sounds like this is P0?  I will drop others you gave me and do this first.

**Comment by wadepickett** [comment] 2019-09-26 23:05
@Rick-Anderson , thanks!  What priority is this?

**Comment by wadepickett** [comment] 2019-10-24 21:25
On this one now.  I had to complete other work that was already in my queue before I could move to this one and was OOF for a week.

**Closed** 2019-11-14 05:11 UTC
Labels: P1, Source - Docs.ms, doc-bug, gRPC
