### ISSUE TITLE
Migration 2.2 -> 3.0 document AllowSynchronousIO now false by default

### ISSUE THREAD

**Issue by mrgleba** [aspnet/AspNetCore.Docs#14222] opened 2019-09-08 20:26 UTC
In 3.0 release ```AllowSynchronousIO``` is false by default. This should be documented in the migration docs.

I'd be also worth mentioning that code like 
```cs
using (var se = new StreamWriter(fs, Encoding.UTF8))
    await se.WriteAsync("...");
```
 should be converted to
```cs
await using (var se = new StreamWriter(fs, Encoding.UTF8))
    await se.WriteAsync("...");
```
as the former still can produce sync writes and the latter is new in 8.0 and may be unfamiliar to many users.

**Comment by guardrex** [comment] 2019-09-09 16:46
Duplicate of https://github.com/aspnet/AspNetCore.Docs/pull/13775 and https://github.com/aspnet/AspNetCore.Docs/issues/12923. Should be updated by the end of the week 🤞.

**Closed by guardrex** 2019-09-09 16:46 UTC
