### ISSUE TITLE
How to read appSettings.{environment} from ConfigureWebHost?

### ISSUE THREAD

**Issue by alvipeo** [aspnet/AspNetCore.Docs#13427] opened 2019-07-22 19:36 UTC
I need it because I use real Db for testing (create and drop). Here's my custom factory:

```
    public class CustomWebApplicationFactory&lt;TStartup&gt; : WebApplicationFactory&lt;TStartup&gt; where TStartup : class
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            //IConfigurationRoot configuration = new ConfigurationBuilder()
            //    .AddJsonFile("appsettings.json", true, true)
            //    .AddJsonFile("appsettings.Local.json", true, true)
            //    .Build();

            builder.ConfigureAppConfiguration((hostingContext, config) =&gt;
                {
                    IHostingEnvironment env = hostingContext.HostingEnvironment;
                    config.AddJsonFile("appsettings.json", true, true)
                        .AddJsonFile("appsettings.Local.json", true, true)
                        .AddJsonFile($"appsettings.{env.EnvironmentName}.json", true, true);
                    config.AddEnvironmentVariables();
                });

                string connectionString = builder.GetSetting("IlgCMSDatabase"); // ====&gt; NULL

                builder.ConfigureServices(services =&gt;
                {
                    ServiceProvider serviceProvider = new ServiceCollection()
                        .AddEntityFrameworkMySQL()
                        //.AddEntityFrameworkInMemoryDatabase()
                        .BuildServiceProvider();


                    // Add a database context using an in-memory 
                    // database for testing.
                    services.AddDbContext&lt;IIlgCmsDbContext, IlgCmsDbContext&gt;(options =&gt;
                    {
                        // options.UseInMemoryDatabase("InMemoryDbForTesting");
                        options.UseMySQL(connectionString); // configuration.GetConnectionString("IlgCMSDatabase")
                        options.UseInternalServiceProvider(serviceProvider);
                    });
                });
        }
    }
```

`connectionString` is always NULL. So how can I do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-07-22 19:39
Since setting the environment sets the configuration file, this is a duplicate of https://github.com/aspnet/AspNetCore.Docs/issues/12303. There's some info there that might help you. Engineering will triage and work all Integration Testing issues going forward. You can check the issue list on the Integration Testing project to see what they'll be considering for docs :point_right: https://github.com/aspnet/AspNetCore.Docs/projects/31

**Closed by guardrex** 2019-07-22 19:39 UTC
Labels: Source - Docs.ms
