### ISSUE TITLE
Shift+Alt+D Doesn't Do Anything

### ISSUE THREAD

**Issue by djbreen7** [aspnet/AspNetCore.Docs#13548] opened 2019-07-30 05:50 UTC
Shift+Alt+D Doesn't Do Anything. Additionally, no message is initially displayed in the console with the instructions as stated in the presentation by Steve Sanderson.

Chrome 75
Ubuntu 18.04.2
.NET Core 3.0.100-preview7-012821
Blazor 3.0.0-preview7.19365.7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-07-30 10:22
@danroth27 It looks like our guidance has regressed. I don't get the new tab in Chrome that explains how to enable debugging now when pressing Shift+Alt+D

When I try to do it manually ... e.g. ...

```console
"%programfiles(x86)%\Google\Chrome\Application\chrome.exe" –remote-debugging-port=9222 http://localhost:5000/
```

... it doesn't work, including after closing the Chrome instance that VS spawns.

**Comment by danroth27** [comment] 2019-07-31 05:56
It works fine for me. Please note this gesture is only used for Blazor WebAssembly Apps (i.e. client-side Blazor apps). Blazor Server Apps just use the normal .NET debugging support in VS. Are you sure you created a Blazor WebAssembly App?

**Comment by guardrex** [comment] 2019-07-31 12:10
Strange ... it used to work for me. I'll try again.

**Comment by djbreen7** [comment] 2019-07-31 13:11
@danroth27 @guardrex 
I'm using client-side according to the list of templates in `dotnet new`

```
Templates                                              Short Name
--------------------------------------------------------------------------
Blazor (client-side)                     blazor
Blazor (server-side)                     blazorserverside
Blazor (ASP.NET Core hosted)             blazorhosted
Blazor Library                           blazorlb
```

These are my steps:

- `dotnet new blazor --name=MyBlazorApp`
- `cd MyBlazorApp`
- `dotnet run` (default configuration is debug)
- `SHIFT`+`ALT`+`D` with focus on the application

Is it possible the the docs incorrectly imply support on Linux?

> With the keyboard focus on the app (not in the developer tools panel, which you should probably close for a less confusing debugging experience), select the following Blazor-specific keyboard shortcut:
> * Shift+Alt+D on Windows/Linux
> * Shift+Cmd+D on macOS

**Comment by guardrex** [comment] 2019-07-31 16:41
@djbreen7 AFAIK, it should work on Linux ... but **_with Chrome_** as the doc states.

This **did** work for me a while back ... it didn't work yesterday. I hope to be free later this afternoon to give it another shot. "*In Dan We Trust!*" ... that's what they print on MS 💵. If he says it works, it works.

I'll ping u back here in a bit. 🏃

**Comment by guardrex** [comment] 2019-07-31 20:38
@danroth27 No 🎲🎲 here.

1. `dotnet new blazor`
1. `dotnet run`
1. Open Chrome (v75.0.3770.142 here)
1. Load app at `http://localhost:5000` (I tried HTTPS on 5001, too.)
1. `Inspect` > `Console` tab. Select the app panel.
1. SHIFT+ALT+D

Error in the console ...

<img width="483" alt="Capture" src="https://user-images.githubusercontent.com/1622880/62246143-9fe56780-b3a8-11e9-8a8e-4890accef5a0.PNG">

No tab explaining how to run the app for debug ...

<img width="301" alt="Capture2" src="https://user-images.githubusercontent.com/1622880/62246148-a2e05800-b3a8-11e9-9a56-13c937ae404e.PNG">

When I try the manual approach with the running app ...

```console
"%programfiles(x86)%\Google\Chrome\Application\chrome.exe" –remote-debugging-port=9222 http://localhost:5000/
```

... same result.

**Comment by djbreen7** [comment] 2019-07-31 20:51
@guardrex Great!

I made sure to download full chrome on Ubuntu (as opposed to chromium)- just to check that box in case the question comes up. :)

Also, I'm sure you're repo'ing on Windows, but I believe the manual command on Ubuntu will be via Android Debug Bridge for anyone who happens to come across this thread:

`adb forward tcp:9222 localabstract:chrome_devtools_remote; google-chrome localhost:9222`

**Comment by guardrex** [comment] 2019-07-31 20:59
:rat:🍔 **_Roasted Rat Burgers!_** :rat:🍔 

I just got it running. The trick was to pass the configuration option ...

```console
dotnet run --configuration Debug
```

Sooooo ... Publish assumes Release, and I thought that `run` assumed `Debug`. I'll take a closer look, but it seems that we need to call that out.

**Comment by guardrex** [comment] 2019-07-31 21:02
> -c|--configuration {Debug|Release}

Defines the build configuration. The default value is Debug.

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore21

*Really?* ... didn't work here. I must pass the option explicitly to get debugging going.

Yep ..... double-checked and confirmed. Gotta pass the option to get it working.

This is an engineering issue. @djbreen7, do you want to open it with them, or do you want me to do so?

**Comment by djbreen7** [comment] 2019-07-31 21:07
@guardrex Nice! I'll try that later this evening when I'm on my home dev box.

I'll go ahead and open up the issue.

Thanks for all your help!

**Comment by guardrex** [comment] 2019-07-31 21:08
Sure thing. We'll leave this open. I'll put a temporary patch on the topic and open a new issue to revert the language based on the outcome of the engineering issue. This will close automatically when the PR merges. Thanks for your help.

**Closed** 2019-07-31 22:15 UTC
Labels: Blazor, P0, Source - Docs.ms
