### ISSUE TITLE
Azure App Service provider section needs to updated to reflect recent Azure Portal changes

### ISSUE THREAD

**Issue by bogan** [aspnet/AspNetCore.Docs#12761] opened 2019-06-08 11:06 UTC
The "Azure App Service provider" section refers to the "Diagnostic Logs" section in the Azure Portal. I could not find a Diagnostic Logs section but did find an "App Service logs" section with the same settings described in the documentation. I assume that the Azure Portal has been changed but the documentation has not been updated to reflect the portal changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#built-in-logging-providers)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by serpent5** [comment] 2019-06-08 14:49
Dupe of #12747.

**Comment by davidfowl** [comment] 2019-06-08 16:13
Yes this changed in the last week or so

**Comment by tdykstra** [comment] 2019-06-10 21:42
@bogan Thanks for reporting this, I'm fixing it now.

**Closed** 2019-06-10 21:43 UTC
Labels: P2, Source - Docs.ms
