### ISSUE TITLE
Minor issue with JavaScript file path

### ISSUE THREAD

**Issue by khrismuc** [aspnet/AspNetCore.Docs#15879] opened 2019-11-26 20:26 UTC
The instructions say to create a file called site.js in the wwwroot folder, but the HTML file expects site.js to be in a subfolder called "js". This stumped at least one person, as can be seen here: https://stackoverflow.com/questions/59033612/how-do-i-solve-the-referenceerror-in-my-api-calls-from-my-ui

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c31071a6-97f2-d0ae-22a7-10e461a3c679
* Version Independent ID: d3227595-fe2a-7630-0379-8da3b1dba2ee
* Content: [Tutorial: Call an ASP.NET Core web API with JavaScript](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/web-api-javascript?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/web-api-javascript.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/web-api-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment] 2019-11-26 20:32
Closing as a duplicate of https://github.com/aspnet/AspNetCore.Docs/issues/14620. I'll address the issue over there right now.

**Closed by scottaddie** 2019-11-26 20:32 UTC
Labels: Source - Docs.ms, duplicate
