### ISSUE TITLE
Wrong return type

### ISSUE THREAD

**Issue by DrGriff** [aspnet/AspNetCore.Docs#15753] opened 2019-11-19 12:06 UTC
Where you have the method:

`public static Task Focus(this ElementReference elementRef, IJSRuntime jsRuntime)
{
    return jsRuntime.InvokeAsync&lt;object&gt;(
        "exampleJsFunctions.focusElement", elementRef);
}`

I think  you need to return `ValueTask&lt;object&gt;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1#capture-references-to-elements)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-11-19 12:57
Hello @DrGriff ... This is a duplicate of https://github.com/aspnet/AspNetCore.Docs/issues/14739. Engineering will look at that shortly and get back to us.

The approach shown in the topic was approved by engineering on several reviews going back into Blazor's beta releases. When the 3.0 was released and Blazor Server went into general availability, this topic was reviewed by engineering along with the rest. They didn't request a change on that review either.

Keep an :eye: on #14739, and we'll see what they say and work it from there. Thanks for commenting.

**Closed by guardrex** 2019-11-19 12:57 UTC
Labels: :watch: Not Triaged, Blazor, Source - Docs.ms
