### ISSUE TITLE
DI in Startup constructor will throw exception in .NET Core 3.0 preview 7

### ISSUE THREAD

**Issue by EdiWang** [aspnet/AspNetCore.Docs#13469] opened 2019-07-24 06:53 UTC
```
public Startup(IConfiguration configuration, ILogger&lt;Startup&gt; logger)
```
This code no longer works. Same issue as https://github.com/aspnet/Extensions/issues/1096

Per Andrew Stanton-Nurse's comment under that issue. https://github.com/aspnet/Extensions/issues/1096#issuecomment-489378332 

This document needs update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment] 2019-07-24 11:35
Hello @EdiWang ... This is a duplicate of our issue to work the whole topic for 3.0. I'll move your remark to that issue.

**Closed by guardrex** 2019-07-24 11:35 UTC
Labels: Source - Docs.ms
