### ISSUE TITLE
Duration and Any types are not defined!

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore.Docs#14624] opened 2019-09-26 05:59 UTC
I need to use Duration and Any types but I get undefined compilation error. What do I miss?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e072aff-35c1-1fc2-3f94-97dc7a809414
* Version Independent ID: 2f05b9da-0d50-ce84-d6af-332da7d9d625
* Content: [gRPC services with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/grpc/aspnetcore.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/aspnetcore.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by JunTaoLuo** [comment] 2019-09-26 20:04
Duplicate of https://github.com/aspnet/AspNetCore.Docs/issues/14627#issuecomment-535395898? If not so, please re-open.

**Closed by JunTaoLuo** 2019-09-26 20:04 UTC
Labels: Source - Docs.ms
