### ISSUE TITLE
Missing instruction to enable 'Use previews of the .NET core SDK' in tools > options

### ISSUE THREAD

**Issue by Wimpje** [aspnet/AspNetCore.Docs#11802] opened 2019-04-03 08:16 UTC
For more info see: https://github.com/aspnet/AspNetCore/issues/8074

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdcc295-2262-311c-99d4-7ece67c5f6ed
* Version Independent ID: 20152398-0971-0302-21f8-b17308f02183
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/spa/blazor/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-04-03 14:07
Hello @Wimpje ... I think we were fine up until yesterday because ...

> For preview releases of Visual Studio, the tools will continue to consume the latest preview version of the SDK that is installed on your machine by default. You cannot change the option to turn this off for preview releases of Visual Studio because they usually require a corresponding preview SDK to work correctly.

... from https://devblogs.microsoft.com/dotnet/net-core-tooling-update-for-visual-studio-2017-version-15-9/.

We don't generally document previews; but since RC/Blazor is *only preview* until 3.0 RTM and VS2019 is out, it makes sense.

I note an error tho with my new VS2019 install. When I set that checkbox, I get an error ...

> A process used by Visual Studio has encountered an unrecoverable error. We recommend saving your work, and then closing and restarting Visual Studio.

(Nice comma splice there! :smile: lol)

An error file produced by VS claims ...

```
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Editor.Razor.LegacyProjectEngineFactory_3_0.<>c__DisplayClass1_0.<Create>b__0(RazorProjectEngineBuilder b)
   at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Create(RazorConfiguration configuration, RazorProjectFileSystem fileSystem, Action`1 configure)
   at Microsoft.VisualStudio.Editor.Razor.LegacyProjectEngineFactory_3_0.Create(RazorConfiguration configuration, RazorProjectFileSystem fileSystem, Action`1 configure)
   at Microsoft.CodeAnalysis.Razor.DefaultProjectSnapshotProjectEngineFactory.Create(RazorConfiguration configuration, RazorProjectFileSystem fileSystem, Action`1 configure)
   at Microsoft.CodeAnalysis.Razor.ProjectSnapshotProjectEngineFactory.Create(RazorConfiguration configuration, String directoryPath, Action`1 configure)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.ProjectState.CreateProjectEngine()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.ProjectState.get_ProjectEngine()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.ProjectState.GetImportDocumentTargetPaths(String targetPath)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.ProjectState.WithAddedHostDocument(HostDocument hostDocument, Func`1 loader)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.DocumentAdded(HostProject hostProject, HostDocument document, TextLoader textLoader)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.RazorProjectHostBase.AddDocumentUnsafe(HostDocument document)
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultRazorProjectHost.<>c__DisplayClass5_1.<OnProjectChanged>b__2()
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.RazorProjectHostBase.<UpdateAsync>d__17.MoveNext()
```

I'll be OOF for a couple of hours and back to work this issue further.

**Comment by Wimpje** [comment] 2019-04-03 14:19
Awesome, thanks for replying so quickly & looking into this. I just installed the non-preview of VS2019 to test out Blazor :) (I like it!) 

I did not have the crash issue btw... (VisualStudio.16.Release/16.0.0+28729.10)

**Comment by guardrex** [comment] 2019-04-03 14:25
I was specifically holding off on installing VS until the release because it *almost* always goes very smoothly. This time tho ... ei ei ei ... not so lucky this time.

I'll research that error when I get back and see if I can put things right (perhaps a VS repair will fix it). I'll get a PR in to cover the checkbox as soon as I determine that it isn't a wider VS problem. If it is a wider VS problem with some sort of caveat (something that I did wrong or didn't do during my VS install ... or perhaps something having to do with the .NET Core runtimes/SDKs on my machine), then that will need to go into the doc, too.

**Comment by guardrex** [comment] 2019-04-03 23:14
ok ... a VS repair seems to have done the trick.

**_Confirmed!_** I'll a bit on this to the topic. Thanks for opening @Wimpje!

**Comment by burrowsUW** [comment] 2019-04-05 18:48
The "Use previews of the .NET Core SDK" tripped me up with my install of VS 2019 (final). I just cannot remember that I did it at the begin of the preview releases so I concur that as long as the required SDK is in prview, the Blazer docs need to remind us of the need to check the box.

**Comment by guardrex** [comment] 2019-04-05 19:05
Yes ... on the way for sure. We have 6 PRs with good Preview 3 updates and some content organizational changes. They should be reviewed and merged soon. Engineering was very 🏃🏃🏃😅 for the VS2019 release, and they'll get to these asap.

**Closed** 2019-04-06 22:31 UTC
Labels: P0, Razor Components, Source - Docs.ms
