### ISSUE TITLE
Azure Key Vault Configuration 3.0 updates

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/AspNetCore.Docs#12346] opened 2019-05-09 01:55 UTC
* Mention change detection
* Update `At the time of writing, the latest stable release of `
related to #12161
* see https://github.com/aspnet/Extensions/pull/1054
* the `reloadOnChange` functionality slated for the .NET Core 3.0 release

![image](https://user-images.githubusercontent.com/3605364/57474014-de95d680-722c-11e9-9253-032c2a3404d3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.1&branch=pr-en-us-12345#feedback)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-05-28 18:21
Two more updates in this vein ...

* Version the content on KV change detection in the Configuration topic. Line 99.
* Scenario where KV access is removed for the application while running ... result is a (silent) reload error and the app continues to use the cached value until restarted.

**Comment by guardrex** [comment] 2019-07-16 19:47
Attempted to work this forward, but it's a :boom: festival on Azure Apps. SCD broke, and FDD can't run on Pre6 right now ...

<img width="401" alt="Capture" src="https://user-images.githubusercontent.com/1622880/61324638-8b19a900-a7d8-11e9-97ba-415c50eb1bb8.PNG">

I'll push this back to RC and hope for better luck then.

**Comment by guardrex** [comment] 2019-10-22 22:18
@natemcmaster @ryanbrandenburg @JunTaoLuo Does this ring a :bell: with you ...

I'm getting the following exception when trying to use a cert from the cert store with the AKV configuration provider while trying to upgrade our sample app to 3.0 ...

> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationOptions.GetTokenFromClientCertificate(String authority, String resource, String clientId, X509Certificate2 certificate)

I see chatter about it in issues (some old) ...

* https://github.com/Azure/azure-sdk-for-media-services/issues/191
* https://github.com/Azure/azure-sdk-for-net/issues/4574
* https://github.com/Azure/azure-sdk-for-media-services/issues/191

The host builder looks like this ....

```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((context, config) =>
        {
            var builtConfig = config.Build();

            using (var store = new X509Store(StoreName.My,
                StoreLocation.CurrentUser))
            {
                store.Open(OpenFlags.ReadOnly);
                var certs = store.Certificates
                    .Find(X509FindType.FindByThumbprint,
                        builtConfig["AzureADCertThumbprint"], false);

                config.AddAzureKeyVault(
                    $"https://{builtConfig["KeyVaultName"]}.vault.azure.net/",
                    builtConfig["AzureADApplicationId"],
                    certs.OfType<X509Certificate2>().Single());

                store.Close();
            }
        })
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
```

I see that `Microsoft.Azure.Services.AppAuthentication/1.3.1` uses `"Microsoft.IdentityModel.Clients.ActiveDirectory": "4.3.0"` and wonder if that should be [Microsoft.IdentityModel.Clients.ActiveDirectory version 5.2.3 (or 5.2.0 with roll-forward behavior)](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/5.2.3)?

One of the issue remarks is ...

> This seems to be fixed in version 5.2.0

**Comment by redshiftz** [comment] 2019-10-30 17:55
Except it's not fixed in 5.2.0 or 5.2.3. I'm still getting this error. 
Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.14.2.11,

If the linkage is still an issue after all this time, perhaps it's time to abandon Microsoft.IdentityModel.Clients.ActiveDirectory and create a new client for IConfiguration to AzureKeyVault? It's just a webapi after all...

**Comment by guardrex** [comment] 2019-10-30 17:57
@redshiftz Can u use a managed identity? ... it worked when I tested it that way.

**Comment by guardrex** [comment] 2019-10-30 17:57
I can put the sample up on GH if you want to see the updated version that worked.

**Comment by redshiftz** [comment] 2019-10-30 18:34
@guardrex A sample would be nice. Maybe it would point out where the problem lies in more detail. 

I do use managed identity when its deployed to Azure, but for debug on my laptop I'm using certificates to authenticate to keyvault. It seemed to be the best way to configure in our environment.

**Comment by guardrex** [comment] 2019-10-30 18:42
I can't address the problem. That's for engineering. Certs aren't working, and the issues I linked seem to indicate that there's been some kind of regression in their framework.

The sample that I have wouldn't do you any good if you have Managed Identity working. That's all I have at this point.

If I can't get certs working, then there are three options:

* Wait ... fix it later when engineering helps (or updates the framework). I'll pick up the topic updates for 3.0 when I have an answer from them. This is probably what's going to happen.
* Switch back to username/password *Yikes!* 🤦‍♂ ... that's **not** good.
* Convert the topic to **only** using manged identity (i.e., drop the cert approach). *No!* 🤦‍♂ ... that's **not** good either.

For the moment, I'll wait a bit longer. I'll try to get help on the Azure side shortly.

**Comment by redshiftz** [comment] 2019-10-30 18:52
Frankly, with the history of this issue creeping back in yet again, I'm considering a fourth option. Abandoning Key Vault for another solution that doesn't use that framework. 
Considering switching to HashiCorp Vault...

**Comment by guardrex** [comment] 2019-10-30 18:58
Fair enough. :smile: I'm sure that they'll notice if that happens with a lot of devs. 💸💰

You *could* ... if you want to lean on it bit ... put an issue up (or add to an existing issue) on their Azure engineering repo. The managers and developers over there are :eyes: on their feedback. If you do open an issue with them, please put a "cc: @guardrex" at the bottom ... I'm as stuck, too! :smile: lol

**Comment by redshiftz** [comment] 2019-11-01 16:28
@guardrex What is the engineering repo? I'll certainly give some feedback.

**Comment by guardrex** [comment] 2019-11-01 16:30
@redshiftz I think they work off of this one ...

https://github.com/Azure/azure-sdk-for-net/issues

... but they'll redirect you if that's not the right spot.

Would you mind adding a "cc: @guardrex" to the bottom of your issue if you open one? I'll be able to keep an :eye: on (perhaps contribute to) the discussion.

**Closed** 2019-11-15 15:11 UTC
Labels: 3.0, P1, doc-enhancement
