### ISSUE TITLE
Client Side Authentication

### ISSUE THREAD

**Issue by ecatherman** [aspnet/AspNetCore.Docs#13601] opened 2019-08-01 12:59 UTC
While it is good to see the warning that you can't trust client side authentication, It does not have any useful information about how to do authentication in the client side. 

Client side authentication and security is about preventing the users that are not trying to hack your program from seeing the server side authentication errors.

I would like to see some examples of how to do that.

Client side C# code is the whole point of Blazor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment] 2019-08-01 15:06
Hello @ecatherman ... This is more of an engineering scenario than a docs scenario at this point. We have https://github.com/aspnet/AspNetCore.Docs/issues/13022 to work the scenario forward on our side when engineering comes up with approaches (if management decides to proceed; our docs issue is still in triage). Although I'm going to close this as a duplicate of #13022, these will be linked, so your remark here will be seen when management triages that issue.

Over on the engineering side, they have several open issues. Try these, and your feedback is welcome over there, so feel free to discuss the scenario with them. You'll be chatting directly with the engineers and managers there.

https://github.com/aspnet/AspNetCore/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aarea-blazor+client-side+authentication

... also click the **Closed** tab on that to see what they either already did (perhaps for an upcoming preview) or refused to take on at this time. They sometimes offer advice on closed issues when they decide not to take something on, too.

**Closed by guardrex** 2019-08-01 15:06 UTC
Labels: Source - Docs.ms

**Comment by guardrex** [comment] 2019-08-01 15:10
... and on that docs issue (#13022), you can add a :+1: to the initial comment message. One other dev already did so. That helps a little bit when they look to gauge the priority.
