### ISSUE TITLE
process of deployment while using "dotnet new react"

### ISSUE THREAD

**Issue by vejandla** [aspnet/AspNetCore.Docs#12582] opened 2019-05-29 13:39 UTC
first of all apologies for the long message

I'm using react template for .net core MVC application. Everything is working fine as expected. The current process we have for dynamic environment variables is

**For .net core webapi** We build the application and then deploy the same build package (do not build again and again per environment) to DEV/QA/UAT/STAGING/PROD by changing the variables in appsettings.json

**For react app**, we have a file in public folder where we maintain a set of variables that needs to be changed per environment, just a simple object that gets assigned to window.___settings variable. and we internally assign this to settings object of our app. This is also working perfectly fine.

**the problem here is**, when we are building and publishing we are using traditional dotnet publish command and it internally calls "react-scripts build" and spits out the bundle to dist folder and we deploy the app in IIS environment. When we try to access the site, the location for the static files is not relative to build folder, it is just taking it relative to the website. All the source paths in index file point to /main.js but whereas this file lives in some folder under the website root folder. so we are getting 404 status.

**temporary/ugly solution** To overcome this, we are rebuilding the app for each and every environment (which we do not want to do) by setting the homepage URL in the package.json file and this time react-scripts internally add the homepage URL to the main.js file in the index file.

Do we have any meaningful solutions where we do not have to rebuild the app for each environment and simply keep deploying the already built package?

_I hope I made sense and explained my problem clearly and Thanks in advance for patiently reading it._

**Comment by vejandla** [comment] 2019-05-29 21:15
Can this be fixed by changing the rootPath value?

 
      // In production, the React files will be served from this directory
        services.AddSpaStaticFiles(configuration =>
        {
            configuration.RootPath = "ClientApp/Build";
        });

**Comment by scottaddie** [comment] 2019-05-30 20:50
This is a better question for the engineers over at the product repo. Closing as a duplicate of https://github.com/aspnet/AspNetCore/issues/10628.

**Closed by scottaddie** 2019-05-30 20:50 UTC
Labels: P2, PU

**Comment by Johnillo2411** [comment] 2019-08-06 16:05
> first of all apologies for the long message
> 
> I'm using react template for .net core MVC application. Everything is working fine as expected. The current process we have for dynamic environment variables is
> 
> **For .net core webapi** We build the application and then deploy the same build package (do not build again and again per environment) to DEV/QA/UAT/STAGING/PROD by changing the variables in appsettings.json
> 
> **For react app**, we have a file in public folder where we maintain a set of variables that needs to be changed per environment, just a simple object that gets assigned to window.___settings variable. and we internally assign this to settings object of our app. This is also working perfectly fine.
> 
> **the problem here is**, when we are building and publishing we are using traditional dotnet publish command and it internally calls "react-scripts build" and spits out the bundle to dist folder and we deploy the app in IIS environment. When we try to access the site, the location for the static files is not relative to build folder, it is just taking it relative to the website. All the source paths in index file point to /main.js but whereas this file lives in some folder under the website root folder. so we are getting 404 status.
> 
> **temporary/ugly solution** To overcome this, we are rebuilding the app for each and every environment (which we do not want to do) by setting the homepage URL in the package.json file and this time react-scripts internally add the homepage URL to the main.js file in the index file.
> 
> Do we have any meaningful solutions where we do not have to rebuild the app for each environment and simply keep deploying the already built package?
> 
> _I hope I made sense and explained my problem clearly and Thanks in advance for patiently reading it._

I have the same situation, you can explainme exactly the solution you found.
