### ISSUE TITLE
How is this impacted by ASP.NECT COre 3.x ? 

### ISSUE THREAD

**Issue by JiriZidek** [aspnet/AspNetCore.Docs#16387] opened 2020-01-03 12:56 UTC
How is this impacted by ASP.NECT COre 3.x which obsoletes lot of things used in this example ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment] 2020-01-03 14:07
Hello @JiriZidek ... This is a duplicate of #11326, and that's tracked by a tracking issue #16209. You can keep an eye on that tracking issue for further developments.

**Closed by guardrex** 2020-01-03 14:07 UTC
Labels: :watch: Not Triaged, Source - Docs.ms
