### ISSUE TITLE
tutorial fails on mac at the "Add the SignalR client library"

### ISSUE THREAD

**Issue by SogoGolf** [aspnet/AspNetCore.Docs#11350] opened 2019-03-09 08:37 UTC
zsh: command not found: libman

solution is here: https://github.com/aspnet/LibraryManager/issues/367

pls update these docs

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-au/aspnet/core/tutorials/signalr?tabs=visual-studio-code&view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment] 2019-03-20 17:57
@SogoGolf which workflow? VS, VS Code, or CLI?

**Comment by SogoGolf** [comment] 2019-03-21 21:33
hi @bradygaster , VS Code

**Comment by hayashida-katsutoshi** [comment] 2019-03-22 20:46
It does not work with VS on Windows too.
"@aspnet/signalr@1*" is not found.
There is "@aspnet/signalr" and "@aspnet/signalr-client" but both of them cannot be download saying 'The "@aspnet/signalr" library could not be resolved by the "unpkg" provider.

**Comment by hayashida-katsutoshi** [comment] 2019-03-22 21:48
I found that the system environment variable OPENSSL_CONF blocked the package manager. I deleted the variable and then I am able to find the library.

**Comment by bradygaster** [comment] 2019-04-03 21:53
@hayashida-katsutoshi whoa - thanks for that update. Closing this issue per your comment - please re-open and mention me if this is in error.

**Closed by bradygaster** 2019-04-03 21:53 UTC
Labels: SignalR, Source - Docs.ms

**Comment by hayashida-katsutoshi** [comment] 2019-04-03 22:16
When I post the question I thought that it might be the same issue. And it turned out that my problem was Windows specific. I am pretty sure my solution does not work for SogoGolf.

**Comment by simonech** [comment] 2019-11-23 09:55
@bradygaster I think the problem is still relevant, not same reason tho. `libman` won't install correctly (with the VSCode flow) on MacOS with Catalina. With Catalina, the default shell is zsh, and the dotnet CLI cannot install global tools when using zsh.

**Comment by bradygaster** [comment] 2019-12-02 20:25
@simonech that's great info. sad, but very helpful info for sure. Will look into this with the tooling teams who write the libman tools. Adding @jodavis and @vijayrkn here as FYI.
