### ISSUE TITLE
Batch Send Emails with Confirmation Links

### ISSUE THREAD

**Issue by neosri** [aspnet/AspNetCore.Docs#12002] opened 2019-04-16 19:44 UTC
Hello,
I am trying to register a set of users in an Console Application(automated) and then send out confirmation emails. Users who get email will confirm the address by opening the link to a web application.So Token in generated in Console Application and confirmation happens in The web application. Now  when i try this using the same identity database, i get invalid token error. I read that the User Manager instance should be the same for generating the token and confirming the account.

How can we share the token between apps that reside on different servers. Or if sharing is not possible, how can we automate token generation without manual intervention?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by WChangming** [comment] 2019-10-26 17:52
In my development (localhost), the Register confirmation email through sendgrid can be sent and confirmed. But after Publish (in production environment), the Register confirmation email is not sent any more. What would be the problem?

**Comment by Rick-Anderson** [comment] 2019-11-06 21:30
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Closed by Rick-Anderson** 2019-11-06 21:30 UTC
Labels: P2, PU, Source - Docs.ms, support-request

**Comment by neosri** [comment] 2019-11-06 21:45
Thanks for your response.I managed to create one.

**Comment by paultechguy** [comment] 2020-04-17 20:10
@neosri, wondering how you were able to generate the token manually?  I want to have a batch console app send confirmation emails to people who never completed their original register/email?  I also get "invalid token".  I am assuming this is because the UserManager was different in console vs. web (where confirm is done).

**Comment by neosri** [comment] 2020-04-18 16:41
Hi there.
You can do that by setting the following in the console and the application where users register/login.Add the middleware like below. Please use the same application name. 
  services.AddDataProtection()
        .SetApplicationName("shared app name")
.PersistKeysToAzureBlobStorage(container, "keys.xml");//can be any mechanism mentioned below

there are different ways to secure and persist the keys(certificates, Azure blob storage, REDIS cache,SQL database using EF core etc..). By this way, you are making sure both the applications are on the same page.They look at the same master key to generate the token.
Reference:
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-3.1&tabs=visual-studio
